# Generated by Django 6.0.1 on 2026-01-20 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='genre',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
