# Generated by Django 6.0.1 on 2026-01-20 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_game_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
